# Generated by Django 6.0 on 2026-01-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
