# Generated by Django 6.0 on 2026-01-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
