# Generated by Django 5.2.6 on 2026-02-13 15:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productgallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_image'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='images',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='gallery_image'),
        ),
    ]
