# Generated by Django 5.2.6 on 2026-02-13 15:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='category_image'),
        ),
    ]
