# Generated by Django 6.0 on 2026-02-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_checkoutdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='delivery_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
