# Generated by Django 6.0 on 2026-01-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Verifying Payment', 'Verifying Payment'), ('Shipping', 'Shipping'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='Verifying Payment', max_length=20),
        ),
    ]
