# Generated by Django 5.2.6 on 2026-02-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_monetaryfields'),
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
    ]
